[package]
name = "shiromana-rs"
version = "0.1.0"
authors = ["Oyami-Srk <hhx.xxm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.24.2"
uuid = "0.8.2"